import * as React from 'react';
import Head from 'next/head'

import { useCookies } from 'react-cookie';
import { API } from '../api/base.js';

import LoginForm from '../components/LoginForm'
import ProjectForm from '../components/ProjectForm'

export default function Admin({auth}) {

  const [cookie, setCookie, removeCookie] = useCookies(['user']);
  const [isLoggedIn, setLogin] = React.useState(auth);

  if (!isLoggedIn) {
    removeCookie('authToken');
  }

  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { isLoggedIn ? <ProjectForm setLogin={setLogin} /> : <LoginForm setLogin={setLogin}/> }

    </div>
  )
}

export const getServerSideProps = async ({req}) => {

  try {
    
    if (!req.cookies.authToken) {
      return { props: { 'auth': false } };
    }
  
    const body = { 'authToken': req.cookies.authToken };
    const res = await API.post('/user/validate-token', body);
  
    if (res.data.authenticated) {
      return { props: { 'auth': true } };
    } else {
      return { props: { 'auth': false } };
    }

  } catch (error) {
    
    console.log("Something went wrong during authentication api call:", error);
    return { props: { 'auth': false } };
  }
}