import * as React from 'react';

import Head from 'next/head'
import LoginForm from '../components/LoginForm'
import ProjectForm from '../components/ProjectForm'

// const doAuth = async () => {

//   const res = await fetch(`http://localhost:3000/api/auth`, {

//     method: "post",
//     headers: {
//       'Accept': 'application/json',
//       'Content-Type': 'application/json'
//     },

//     body: JSON.stringify({
//       authToken: cookie.authToken,
//     })
//   });

//   const retval = await res.json();

//   if (cookie.authToken === "lol69") {
//     initLog = true;
//   }
// }

export default function Admin({auth}) {

  const [isLoggedIn, setLogin] = React.useState(auth);

  console.log(isLoggedIn);

  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { isLoggedIn ? <ProjectForm setLogin={setLogin} /> : <LoginForm setLogin={setLogin}/> }

    </div>
  )
}

export const getServerSideProps = async ({req}) => {
  
  console.log(req.cookies.authToken);

  var auth = false;

  if (req.cookies.authToken) {
   auth = true;
  }

  return { props: { auth } }
}