import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Projects() {
  
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <h1>projects</h1>
    </div>
  )
}