import Head from 'next/head'
import NavBar from '../components/NavBar'
import Card from '../components/Card'

import styles from '../styles/RandPassGen.module.css'

export default function Projects() {
  
  const object = {
    title: 'Some title goes here.',
    link: 'https://www.github.com/jp-val',
    description: 'And then some description would go here cuz where else would it go? lmao.'
  }

  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      
      <h1>projects</h1>

      <div className={styles.grid}>
        <Card object={object} />
        {/* <Card />
        <Card />
        <Card /> */}
      </div>

    </div>
  )
}