import Head from 'next/head'
import DenseTable from '../components/Table'
import styles from '../styles/Home.module.css'

export default function Rankings({ranking}) {
  
  return (
    <div>
      <Head>
        <title>CFB Rankings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>cfb rankings</h1>

      <div className={styles.rankings}>
        <DenseTable {...ranking} />
        <DenseTable {...ranking} />
        <DenseTable {...ranking} />
        <DenseTable {...ranking} />
        <DenseTable {...ranking} />
      </div>
    </div>
  )
}

export const getStaticProps = async () => {
  
  const res = await fetch(`http://localhost:3000/api/hello`)
    const ranking = await res.json()
    console.log(ranking)
    
  return { props: { ranking } }
}