import Head from 'next/head'

export default function Template() {
  
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>template</h1>
    </div>
  )
}