import Head from 'next/head'

import AdminNavBar from '../../components/AdminNavBar'

export default function Articles() {
  
  return (
    <div>
      <Head>
        <title>Artciles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AdminNavBar />
      <h1>Articles</h1>
    </div>
  )
}