import * as React from 'react';
import Head from 'next/head';

import { useCookies } from 'react-cookie';
import { API } from '../../api/base.js';

import LoginForm from '../../components/LoginForm';
import AdminNavBar from '../../components/AdminNavBar';

export const getServerSideProps = async ({req}) => {

  try {
    
    // console.log(req.headers['user-agent']);

    if (!req.cookies.authToken) {
      return { props: { 'auth': false } };
    }

    const body = { 'authToken': req.cookies.authToken };
    const res = await API.post('/user/validate-token', body);
  
    if (res.data.authenticated) {
      return { props: { 'auth': true } };
    } else {
      return { props: { 'auth': false } };
    }

  } catch (error) {
    
    console.log("Something went wrong during authentication api call:", error);
    return { props: { 'auth': false } };
  }
}

export default function Admin({ auth }) {

  const [cookie, setCookie, removeCookie] = useCookies(['user']);
  const [isLoggedIn, setLogin] = React.useState(auth);

  if (!isLoggedIn) {
    removeCookie('authToken');
  }

  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { isLoggedIn ? <AdminNavBar setLogin={setLogin} /> : null }
      { isLoggedIn ? <h1>Admin Dashboard</h1> : <LoginForm setLogin={setLogin}/> }
    
    </div>
  )
}