import Head from 'next/head'

import ProjectForm from '../../components/ProjectForm';

// export const getServerSideProps = async ({req}) => {
  
//   if (!req.cookies.authToken) {
//     return {
//       redirect: {
//         destination: '/admin'
//       }
//     }
//   }
// };

export default function NewProjectForm() {
  
  return (
    <div>
      <Head>
        <title>Project Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Project Form</h1>
      <ProjectForm />
    </div>
  )
}